package com.dfwcomputech.japp.remotecontract;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-03-13T15:04:17.864-05:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://remotecontract.japp.dfwcomputech.com", name = "JAppService")
@XmlSeeAlso({ObjectFactory.class})
public interface JAppService {

    @WebResult(name = "getCurrentUserResponse", targetNamespace = "")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://remotecontract.japp.dfwcomputech.com", className = "com.dfwcomputech.japp.remotecontract.GetCurrentUser")
    @WebMethod
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://remotecontract.japp.dfwcomputech.com", className = "com.dfwcomputech.japp.remotecontract.GetCurrentUserResponse")
    public com.dfwcomputech.japp.remotecontract.JAppUser getCurrentUser();
}
