package com.dfwcomputech.japp.remotecontract;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-03-13T16:26:03.907-05:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://remotecontract.japp.dfwcomputech.com", name = "MyWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface MyWebService {

    @WebResult(name = "loginResponse", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://remotecontract.japp.dfwcomputech.com", className = "com.dfwcomputech.japp.remotecontract.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://remotecontract.japp.dfwcomputech.com", className = "com.dfwcomputech.japp.remotecontract.LoginResponse")
    public com.dfwcomputech.japp.remotecontract.UserSession login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
